export const dalleSupriseMePrompts = [
    "Depict a dramatic battle scene between two mythical creatures.",
    "Create an abstract painting that evokes the feeling of freedom.",
    "Illustrate a magical forest full of whimsical creatures and plants.",
    "Design an otherworldly spaceship for a sci-fi movie.",
    "Paint a portrait of an elderly person and capture their wisdom and experience.",
    "Draw a futuristic cityscape with towering skyscrapers and neon lights.",
    "Create a mixed media piece inspired by the concept of time.",
    "Depict a serene countryside landscape with rolling hills and a clear blue sky.",
    "Design an intricate mandala with intricate patterns and symbols.",
    "Paint a still life of a bowl of fruit with rich colors and textures.",
    "Illustrate a majestic dragon soaring through the clouds.",
    "Create a digital illustration of a bustling marketplace in a foreign land.",
    "Depict a mystical underwater world with mermaids and sea creatures.",
    "Design a whimsical illustration for a children's book.",
    "Paint a landscape of a quiet winter night with snow-covered trees and a full moon.",
    "Draw a surreal portrait of a person with a unique personality.",
    "Create a sculpture of an animal that represents strength and power.",
    "Illustrate a post-apocalyptic world with a stark, desolate landscape.",
    "Design a cover for a fantasy novel with intricate details and symbols.",
    "Paint a portrait of a person with a kind and compassionate soul.",
    "Depict a dramatic stormy sea with crashing waves and dark skies.",
    "Create a mixed media piece that represents the concept of rebirth.",
    "Illustrate a bustling city street with people from different cultures and backgrounds.",
    "Design an intricate tattoo inspired by nature.",
    "Paint a still life of a bouquet of flowers with soft colors and delicate brushstrokes.",
    "Draw a whimsical scene of a fantastical creature interacting with everyday objects.",
    "Create a digital illustration of a fantastical castle on a mountaintop.",
    "Depict a mystical forest with glowing mushrooms and hidden secrets.",
    "Design a surreal landscape inspired by dreams and the subconscious mind.",
    "Paint a portrait of a person with a fierce determination and passion.",
    "Illustrate a fantastical world with mythical creatures and magical spells.",
    "Create a sculpture of a person with a complex emal inner world.",
    "Depict a serene beach with turquoise waters and palm trees.",
    "Design an intricate pattern inspired by the natural world.",
    "Paint a landscape of a peaceful countryside with rolling hills and a babbling brook.",
    "Draw a fantastical creature with intricate details and unique characteristics.",
    "Create a mixed media piece that represents the concept of hope.",
    "Illustrate a cityscape at night with glowing lights and reflections in the water.",
    "Design an intricate logo for a new company with a strong brand identity.",
    "Paint a portrait of a person with a mischievous spirit and a twinkle in their eye.",
    "Depict a majestic mountain range with snow-capped peaks and a deep valley below.",
    "Create a digital illustration of a fantastical world with floating islands and airships.",
    "Design a surrealist landscape inspired by the work of Salvador Dali.",
    "Paint a still life of a vase of flowers with bold, vibrant colors.",
    "Illustrate a mythical creature interacting with a real-life animal.",
    "Depict a quiet forest with a gentle stream running through it.",
    "Create a sculpture of an abstract concept, such as love or hope.",
    "Design an intricate tattoo inspired by a piece of literature.",
    "Paint a portrait of a person with a quiet confidence.",
]