export const languages = [
    { language: 'Afrikaans', nativeWriting: 'Afrikaans', direction: 'ltr' },
    { language: 'Albanian', nativeWriting: 'Shqip', direction: 'ltr' },
    { language: 'Amharic', nativeWriting: 'አማርኛ', direction: 'ltr' },
    { language: 'Arabic', nativeWriting: 'العربية', direction: 'rtl' },
    { language: 'Armenian', nativeWriting: 'Հայերեն', direction: 'ltr' },
    { language: 'Assamese', nativeWriting: 'অসমীয়া', direction: 'ltr' },
    { language: 'Azerbaijani', nativeWriting: 'Azərbaycanca', direction: 'ltr' },
    { language: 'Basque', nativeWriting: 'Euskara', direction: 'ltr' },
    { language: 'Belarusian', nativeWriting: 'Беларуская', direction: 'ltr' },
    { language: 'Bengali', nativeWriting: 'বাংলা', direction: 'ltr' },
    { language: 'Bosnian', nativeWriting: 'Bosanski', direction: 'ltr' },
    { language: 'Bulgarian', nativeWriting: 'Български', direction: 'ltr' },
    { language: 'Burmese', nativeWriting: 'မြန်မာဘာသာ', direction: 'ltr' },
    { language: 'Catalan', nativeWriting: 'Català', direction: 'ltr' },
    { language: 'Cebuano', nativeWriting: 'Cebuano', direction: 'ltr' },
    { language: 'Chichewa', nativeWriting: 'Chichewa', direction: 'ltr' },
    { language: 'Chinese', nativeWriting: '中文', direction: 'ltr' },
    { language: 'Corsican', nativeWriting: 'Corsu', direction: 'ltr' },
    { language: 'Croatian', nativeWriting: 'Hrvatski', direction: 'ltr' },
    { language: 'Czech', nativeWriting: 'Čeština', direction: 'ltr' },
    { language: 'Danish', nativeWriting: 'Dansk', direction: 'ltr' },
    { language: 'Dutch', nativeWriting: 'Nederlands', direction: 'ltr' },
    { language: 'English', nativeWriting: 'English', direction: 'ltr' },
    { language: 'Esperanto', nativeWriting: 'Esperanto', direction: 'ltr' },
    { language: 'Estonian', nativeWriting: 'Eesti', direction: 'ltr' },
    { language: 'Finnish', nativeWriting: 'Suomi', direction: 'ltr' },
    { language: 'French', nativeWriting: 'Français', direction: 'ltr' },
    { language: 'Frisian', nativeWriting: 'Frysk', direction: 'ltr' },
    { language: 'Galician', nativeWriting: 'Galego', direction: 'ltr' },
    { language: 'Georgian', nativeWriting: 'ქართული', direction: 'ltr' },
    { language: 'German', nativeWriting: 'Deutsch', direction: 'ltr' },
    { language: 'Greek', nativeWriting: 'Ελληνικά', direction: 'ltr' },
    { language: 'Gujarati', nativeWriting: 'ગુજરાતી', direction: 'ltr' },
    { language: 'Haitian Creole', nativeWriting: 'Kreyòl Ayisyen', direction: 'ltr' },
    { language: 'Hausa', nativeWriting: 'هَوُسَ', direction: 'ltr' },
    { language: 'Hawaiian', nativeWriting: 'ʻŌlelo Hawaiʻi', direction: 'ltr' },
    { language: 'Hebrew', nativeWriting: 'עִבְרִית', direction: 'rtl' },
    { language: 'Hindi', nativeWriting: 'हिन्दी', direction: 'ltr' },
    { language: 'Hmong', nativeWriting: 'Hmoob', direction: 'ltr' },
    { language: 'Hungarian', nativeWriting: 'Magyar', direction: 'ltr' },
    { language: 'Icelandic', nativeWriting: 'Íslenska', direction: 'ltr' },
    { language: 'Igbo', nativeWriting: 'Igbo', direction: 'ltr' },
    { language: 'Indonesian', nativeWriting: 'Bahasa Indonesia', direction: 'ltr' },
    { language: 'Irish', nativeWriting: 'Gaeilge', direction: 'ltr' },
    { language: 'Italian', nativeWriting: 'Italiano', direction: 'ltr' },
    { language: 'Japanese', nativeWriting: '日本語', direction: 'ltr' },
    { language: 'Javanese', nativeWriting: 'Basa Jawa', direction: 'ltr' },
    { language: 'Kannada', nativeWriting: 'ಕನ್ನಡ', direction: 'ltr' },
    { language: 'Kazakh', nativeWriting: 'Қазақша', direction: 'ltr' },
    { language: 'Khmer', nativeWriting: 'ភាសាខ្មែរ', direction: 'ltr' },
    { language: 'Kinyarwanda', nativeWriting: 'Kinyarwanda', direction: 'ltr' },
    { language: 'Korean', nativeWriting: '한국어', direction: 'ltr' },
    { language: 'Lao', nativeWriting: 'ລາວ', direction: 'ltr' },
    { language: 'Latvian', nativeWriting: 'Latviešu', direction: 'ltr' },
    { language: 'Lithuanian', nativeWriting: 'Lietuvių', direction: 'ltr' },
    { language: 'Luxembourgish', nativeWriting: 'Lëtzebuergesch', direction: 'ltr' },
    { language: 'Macedonian', nativeWriting: 'Македонски', direction: 'ltr' },
    { language: 'Malagasy', nativeWriting: 'Malagasy', direction: 'ltr' },
    { language: 'Malay', nativeWriting: 'Bahasa Melayu', direction: 'ltr' },
    { language: 'Malayalam', nativeWriting: 'മലയാളം', direction: 'ltr' },
    { language: 'Maltese', nativeWriting: 'Malti', direction: 'ltr' },
    { language: 'Maori', nativeWriting: 'Māori', direction: 'ltr' },
    { language: 'Marathi', nativeWriting: 'मराठी', direction: 'ltr' },
    { language: 'Mongolian', nativeWriting: 'Монгол', direction: 'ltr' },
    { language: 'Nepali', nativeWriting: 'नेपाली', direction: 'ltr' },
    { language: 'Norwegian', nativeWriting: 'Norsk', direction: 'ltr' },
    { language: 'Odia', nativeWriting: 'ଓଡ଼ିଆ', direction: 'ltr' },
    { language: 'Pashto', nativeWriting: 'پښتو', direction: 'rtl' },
    { language: 'Persian', nativeWriting: 'فارسی', direction: 'rtl' },
    { language: 'Polish', nativeWriting: 'Polski', direction: 'ltr' },
    { language: 'Portuguese', nativeWriting: 'Português', direction: 'ltr' },
    { language: 'Punjabi', nativeWriting: 'ਪੰਜਾਬੀ', direction: 'ltr' },
    { language: 'Lao', nativeWriting: 'ລາວ', direction: 'ltr' },
    { language: 'Latin', nativeWriting: 'Latina', direction: 'ltr' },
    { language: 'Latvian', nativeWriting: 'Latviešu', direction: 'ltr' },
    { language: 'Lithuanian', nativeWriting: 'Lietuvių', direction: 'ltr' },
    { language: 'Luxembourgish', nativeWriting: 'Lëtzebuergesch', direction: 'ltr' },
    { language: 'Macedonian', nativeWriting: 'Македонски', direction: 'ltr' },
    { language: 'Malagasy', nativeWriting: 'Malagasy', direction: 'ltr' },
    { language: 'Malay', nativeWriting: 'Bahasa Melayu', direction: 'ltr' },
    { language: 'Malayalam', nativeWriting: 'മലയാളം', direction: 'ltr' },
    { language: 'Maltese', nativeWriting: 'Malti', direction: 'ltr' },
    { language: 'Maori', nativeWriting: 'Māori', direction: 'ltr' },
    { language: 'Marathi', nativeWriting: 'मराठी', direction: 'ltr' },
    { language: 'Mongolian', nativeWriting: 'Монгол', direction: 'ltr' },
    { language: 'Myanmar (Burmese)', nativeWriting: 'မြန်မာဘာသာ', direction: 'ltr' },
    { language: 'Nepali', nativeWriting: 'नेपाली', direction: 'ltr' },
    { language: 'Norwegian', nativeWriting: 'Norsk', direction: 'ltr' },
    { language: 'Odia (Oriya)', nativeWriting: 'ଓଡ଼ିଆ', direction: 'ltr' },
    { language: 'Pashto', nativeWriting: 'پښتو', direction: 'rtl' },
    { language: 'Persian (Farsi)', nativeWriting: 'فارسی', direction: 'rtl' },
    { language: 'Polish', nativeWriting: 'Polski', direction: 'ltr' },
    { language: 'Portuguese', nativeWriting: 'Português', direction: 'ltr' },
    { language: 'Punjabi', nativeWriting: 'ਪੰਜਾਬੀ', direction: 'ltr' },
    { language: 'Quechua', nativeWriting: 'Runa Simi', direction: 'ltr' },
    { language: 'Romanian', nativeWriting: 'Română', direction: 'ltr' },
    { language: 'Russian', nativeWriting: 'Русский', direction: 'ltr' },
    { language: 'Samoan', nativeWriting: 'Gagana Samoa', direction: 'ltr' },
    { language: 'Scots Gaelic (Gaelic)', nativeWriting: 'Gàidhlig', direction: 'ltr' },
    { language: 'Serbian', nativeWriting: 'Српски', direction: 'ltr' },
    { language: 'Shona', nativeWriting: 'ChiShona', direction: 'ltr' },
    { language: 'Sindhi', nativeWriting: 'سنڌي', direction: 'rtl' },
    { language: 'Sinhala (Sinhalese)', nativeWriting: 'සිංහල', direction: 'ltr' },
    { language: 'Slovak', nativeWriting: 'Slovenčina', direction: 'ltr' },
    { language: 'Slovenian', nativeWriting: 'Slovenščina', direction: 'ltr' },
    { language: 'Somali', nativeWriting: 'Soomaali', direction: 'ltr' },
    { language: 'Spanish', nativeWriting: 'Español', direction: 'ltr' },
    { language: 'Sundanese', nativeWriting: 'Basa Sunda', direction: 'ltr' },
    { language: 'Swahili', nativeWriting: 'Kiswahili', direction: 'ltr' },
    { language: 'Swedish', nativeWriting: 'Svenska', direction: 'ltr' },
    { language: 'Tajik', nativeWriting: 'Тоҷикӣ', direction: 'ltr' },
    { language: 'Tamil', nativeWriting: 'தமிழ்', direction: 'ltr' },
    { language: 'Tatar', nativeWriting: 'Татар', direction: 'ltr' },
    { language: 'Telugu', nativeWriting: 'తెలుగు', direction: 'ltr' },
    { language: 'Thai', nativeWriting: 'ไทย', direction: 'ltr' },
    { language: 'Tibetan', nativeWriting: 'བོད་སྐད་', direction: 'ltr' },
    { language: 'Tigrinya', nativeWriting: 'ትግርኛ', direction: 'ltr' },
    { language: 'Tok Pisin', nativeWriting: 'Tok Pisin', direction: 'ltr' },
    { language: 'Turkish', nativeWriting: 'Türkçe', direction: 'ltr' },
    { language: 'Turkmen', nativeWriting: 'Түркмен', direction: 'ltr' },
    { language: 'Ukrainian', nativeWriting: 'Українська', direction: 'ltr' },
    { language: 'Urdu', nativeWriting: 'اردو', direction: 'rtl' },
    { language: 'Uyghur', nativeWriting: 'ئۇيغۇرچە', direction: 'rtl' },
    { language: 'Uzbek', nativeWriting: 'Oʻzbekcha', direction: 'ltr' },
    { language: 'Vietnamese', nativeWriting: 'Tiếng Việt', direction: 'ltr' },
    { language: 'Welsh', nativeWriting: 'Cymraeg', direction: 'ltr' },
    { language: 'Western Frisian', nativeWriting: 'Frysk', direction: 'ltr' },
    { language: 'Xhosa', nativeWriting: 'isiXhosa', direction: 'ltr' },
    { language: 'Yiddish', nativeWriting: 'ייִדיש', direction: 'rtl' },
    { language: 'Yoruba', nativeWriting: 'Yorùbá', direction: 'ltr' },
    { language: 'Zulu', nativeWriting: 'isiZulu', direction: 'ltr' }
  ];
  
  